services:
  foxglove:
    build:
      context: ..
      dockerfile: docker/vis_tools/foxglove.Dockerfile
      cache_from:
        - "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:${TAG}"
        - "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:main"
      args:
        BASE_IMAGE: ${BASE_IMAGE_OVERRIDE-}
    image: "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:${TAG}"
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:?}
    profiles: [deploy, develop]
    command: ["ros2", "launch", "foxglove_bridge", "foxglove_bridge_launch.xml", "port:=${FOXGLOVE_BRIDGE_PORT:?}"]
